spring:
  datasource:
    url: jdbc:sqlserver://swap.database.windows.net:1433;database=swapdb;user=swap@swap;password=Sw@123pniL;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: swap
    password: Sw@123pniL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


